# Generated by Django 5.1 on 2024-09-09 19:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('myApp', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='users_birthdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='users_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='users_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='users_rol',
            field=models.ForeignKey(db_column='users_rol', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.rol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='users_status',
            field=models.ForeignKey(db_column='users_status', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='users_tour',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
