# Generated by Django 5.1 on 2024-09-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='programs_name',
            field=models.CharField(default='Default Program', max_length=255),
            preserve_default=False,
        ),
    ]
