# Generated by Django 5.1 on 2024-09-19 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_add_programs_name_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='days',
            old_name='days_description',
            new_name='day_description',
        ),
        migrations.RenameField(
            model_name='days',
            old_name='days_id',
            new_name='day_id',
        ),
        migrations.RemoveField(
            model_name='days',
            name='days_activity',
        ),
        migrations.CreateModel(
            name='DaysActivities',
            fields=[
                ('days_activities_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('days_activities_activity', models.ForeignKey(db_column='days_activities_activity', on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.activities')),
                ('days_activities_days', models.ForeignKey(db_column='days_activities_days', on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.days')),
            ],
            options={
                'db_table': 'days_activities',
                'managed': True,
            },
        ),
    ]
