# Generated by Django 5.1 on 2024-09-19 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_create_relation_days_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='schedules_day',
            field=models.ForeignKey(db_column='schedules_day', on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.daysactivities'),
        ),
    ]
