# Generated by Django 5.1 on 2024-09-20 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_field_name_correction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='activities_area',
        ),
        migrations.AddField(
            model_name='programs',
            name='programs_area',
            field=models.ForeignKey(db_column='programs_area', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.areas'),
            preserve_default=False,
        ),
    ]
