# Generated by Django 5.1 on 2024-09-26 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_add_fiel_donation_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='bills_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='bills_user',
            field=models.ForeignKey(db_column='bills_user', default=2, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
