# Generated by Django 5.1 on 2024-09-26 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_add_fields_in_bills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancebeneficiaries',
            name='performance_beneficiaries_activity',
        ),
        migrations.RemoveField(
            model_name='performancebeneficiaries',
            name='performance_beneficiaries_children',
        ),
        migrations.CreateModel(
            name='SubscriptionsChildren',
            fields=[
                ('subscriptions_children_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subscriptions_children_activity', models.ForeignKey(db_column='subscriptions_children_activity', on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.activities')),
                ('subscriptions_children_child', models.ForeignKey(db_column='subscriptions_children_child', on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.children')),
            ],
            options={
                'db_table': 'subscriptions_children',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='performancebeneficiaries',
            name='performance_beneficiaries_subscription',
            field=models.ForeignKey(db_column='performance_beneficiaries_subscription', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.subscriptionschildren'),
        ),
        migrations.CreateModel(
            name='SubscriptionsVolunteer',
            fields=[
                ('subscriptions_volunteer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subscriptions_volunteer_activity', models.ForeignKey(db_column='subscriptions_volunteer_activity', on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.activities')),
                ('subscriptions_volunteer_user', models.ForeignKey(db_column='subscriptions_volunteer_user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions_volunteer',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Subscriptions',
        ),
    ]
