# Generated by Django 5.1 on 2024-10-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_hotfix_in_performance_children'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('grades_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('grades_description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'grades',
                'managed': True,
            },
        ),
    ]
