# Generated by Django 5.1 on 2024-10-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_chat_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='messages_date',
            field=models.DateTimeField(),
        ),
    ]
