# Generated by Django 5.1 on 2024-10-18 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_alter_chat_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_user1',
            field=models.ForeignKey(db_column='chat_user1', on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_user2',
            field=models.ForeignKey(db_column='chat_user2', on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messages',
            name='messages_chat',
            field=models.ForeignKey(db_column='messages_chat', on_delete=django.db.models.deletion.CASCADE, to='myApp.chat'),
        ),
    ]
