# Generated by Django 5.1 on 2024-10-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_alter_chat_chat_id_alter_messages_messages_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_seen',
            field=models.BooleanField(default=False),
        ),
    ]
