# Generated by Django 5.1 on 2024-10-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_chat_chat_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='chat_seen',
            new_name='chat_seen_user1',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_seen_user2',
            field=models.BooleanField(default=False),
        ),
    ]
