# Generated by Django 5.1 on 2024-10-25 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_rename_chat_seen_chat_chat_seen_user1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedules',
            old_name='schedules_duration',
            new_name='schedules_end',
        ),
        migrations.RemoveField(
            model_name='schedules',
            name='schedules_day',
        ),
        migrations.AddField(
            model_name='daysactivities',
            name='days_activities_schedules',
            field=models.ForeignKey(db_column='days_activities_day', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.schedules'),
            preserve_default=False,
        ),
    ]
