# Generated by Django 5.1 on 2024-10-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0020_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
