# Generated by Django 5.1 on 2024-11-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_userdata_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='children_curp',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
