# Generated by Django 5.1 on 2024-11-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_alter_children_children_curp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancebeneficiaries',
            name='performance_beneficiaries_value',
            field=models.FloatField(null=True),
        ),
    ]
